import Foundation
import PackagePlugin

/// Build tool plugin that generates version information at compile time
///
/// This plugin extracts git version information during the build process
/// and generates a Swift source file containing compile-time constants
/// for version, commit hash, and build date.
@main
struct GenerateVersionInfo: BuildToolPlugin {
    func createBuildCommands(context: PluginContext, target: Target) async throws -> [Command] {
        guard target is SourceModuleTarget else {
            return []
        }

        let outputPath = context.pluginWorkDirectoryURL.appending(path: "GeneratedVersionInfo.swift")

        // Generate the version info directly in the plugin
        let version = getGitVersion(in: context.package.directoryURL.path())
        let commitHash = getGitCommitHash(in: context.package.directoryURL.path())
        let buildDate = getCurrentDateISO8601()

        let sourceContent = """
        // This file is automatically generated during build. Do not edit manually.

        import Foundation

        /// Compile-time embedded build and version information
        ///
        /// This enum contains version metadata that is generated during the build process
        /// and embedded directly into the binary, ensuring version information is available
        /// even in distributed binaries without access to the git repository.
        public enum BuildInfo {
            /// Git version tag or commit reference
            public static let version: String = "\(version)"

            /// Short git commit hash
            public static let gitCommitHash: String = "\(commitHash)"

            /// ISO 8601 formatted build timestamp
            public static let buildDate: String = "\(buildDate)"

            /// Build configuration (Debug or Release)
            #if DEBUG
            public static let configuration: String = "Debug"
            #else
            public static let configuration: String = "Release"
            #endif
        }
        """

        try sourceContent.write(to: outputPath, atomically: true, encoding: .utf8)

        return [
            .buildCommand(
                displayName: "Generating Version Information",
                executable: URL(fileURLWithPath: "/usr/bin/true"),
                arguments: [],
                inputFiles: [],
                outputFiles: [outputPath]
            )
        ]
    }

    private func runCommand(_ command: String, arguments: [String], in directory: String) -> String? {
        let process = Process()
        let pipe = Pipe()

        process.standardOutput = pipe
        process.standardError = pipe
        process.arguments = arguments
        process.executableURL = URL(fileURLWithPath: command)
        process.currentDirectoryURL = URL(fileURLWithPath: directory)

        do {
            try process.run()
            process.waitUntilExit()

            let data = pipe.fileHandleForReading.readDataToEndOfFile()
            if let output = String(data: data, encoding: .utf8) {
                let trimmed = output.trimmingCharacters(in: .whitespacesAndNewlines)
                return trimmed.isEmpty ? nil : trimmed
            }
        } catch {
            return nil
        }

        return nil
    }

    private func getGitVersion(in directory: String) -> String {
        if let version = runCommand("/bin/sh", arguments: ["-c", "git describe --tags --always 2>/dev/null || git rev-parse --short HEAD 2>/dev/null"], in: directory) {
            return version
        }
        return "unknown"
    }

    private func getGitCommitHash(in directory: String) -> String {
        if let hash = runCommand("/bin/sh", arguments: ["-c", "git rev-parse --short HEAD 2>/dev/null"], in: directory) {
            return hash
        }
        return "Unknown"
    }

    private func getCurrentDateISO8601() -> String {
        let formatter = ISO8601DateFormatter()
        formatter.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        return formatter.string(from: Date())
    }
}
