import XCTest
@testable import Substation

/// Unit tests for compile-time embedded BuildInfo
///
/// These tests verify that the BuildInfo enum generated by the GenerateVersionInfo
/// build plugin contains valid version information that is embedded at compile time.
final class BuildInfoTests: XCTestCase {

    // MARK: - Version Tests

    /// Test that version string is not empty
    func testVersionIsNotEmpty() {
        XCTAssertFalse(BuildInfo.version.isEmpty, "Version should not be empty")
    }

    /// Test that version matches expected git format
    func testVersionFormat() {
        let version = BuildInfo.version

        // Version should either be:
        // 1. "unknown" (if git is not available)
        // 2. A short hash (e.g., "abc1234")
        // 3. A tag with optional commit info (e.g., "v1.0.0" or "v1.0.0-5-gabc1234")

        if version != "unknown" {
            // Should contain only valid git version characters
            let validPattern = "^[a-zA-Z0-9._-]+$"
            let regex = try? NSRegularExpression(pattern: validPattern)
            let range = NSRange(version.startIndex..<version.endIndex, in: version)
            let matches = regex?.firstMatch(in: version, range: range)

            XCTAssertNotNil(matches, "Version '\(version)' should match git version format")
        }
    }

    // MARK: - Commit Hash Tests

    /// Test that commit hash is not empty
    func testCommitHashIsNotEmpty() {
        XCTAssertFalse(BuildInfo.gitCommitHash.isEmpty, "Commit hash should not be empty")
    }

    /// Test that commit hash format is valid
    func testCommitHashFormat() {
        let commitHash = BuildInfo.gitCommitHash

        if commitHash != "Unknown" {
            // Git short hash is typically 7 characters of hex
            // But can be longer if there are collisions
            XCTAssertGreaterThanOrEqual(commitHash.count, 7, "Commit hash should be at least 7 characters")
            XCTAssertLessThanOrEqual(commitHash.count, 40, "Commit hash should not exceed 40 characters")

            // Should only contain hexadecimal characters
            let hexPattern = "^[a-f0-9]+$"
            let regex = try? NSRegularExpression(pattern: hexPattern)
            let range = NSRange(commitHash.startIndex..<commitHash.endIndex, in: commitHash)
            let matches = regex?.firstMatch(in: commitHash, range: range)

            XCTAssertNotNil(matches, "Commit hash '\(commitHash)' should be hexadecimal")
        }
    }

    // MARK: - Build Date Tests

    /// Test that build date is not empty
    func testBuildDateIsNotEmpty() {
        XCTAssertFalse(BuildInfo.buildDate.isEmpty, "Build date should not be empty")
    }

    /// Test that build date is in ISO 8601 format
    func testBuildDateISO8601Format() {
        let buildDate = BuildInfo.buildDate

        // Parse the build date using ISO8601DateFormatter
        let formatter = ISO8601DateFormatter()
        formatter.formatOptions = [.withInternetDateTime, .withFractionalSeconds]

        let date = formatter.date(from: buildDate)
        XCTAssertNotNil(date, "Build date '\(buildDate)' should be valid ISO 8601 format")

        if let date = date {
            // Build date should be in the past or very recent (within last hour)
            let now = Date()
            XCTAssertLessThanOrEqual(date, now.addingTimeInterval(3600),
                                    "Build date should not be more than 1 hour in the future")

            // Build date should not be too old (within last year is reasonable for tests)
            let oneYearAgo = now.addingTimeInterval(-365 * 24 * 3600)
            XCTAssertGreaterThanOrEqual(date, oneYearAgo,
                                       "Build date should not be more than a year old")
        }
    }

    /// Test that build date can be parsed and converted back
    func testBuildDateRoundTrip() {
        let buildDate = BuildInfo.buildDate

        let formatter = ISO8601DateFormatter()
        formatter.formatOptions = [.withInternetDateTime, .withFractionalSeconds]

        guard let date = formatter.date(from: buildDate) else {
            XCTFail("Build date should be parseable")
            return
        }

        let roundTripped = formatter.string(from: date)

        // Should be able to round-trip the date
        XCTAssertEqual(buildDate, roundTripped,
                      "Build date should round-trip through ISO8601DateFormatter")
    }

    // MARK: - Configuration Tests

    /// Test that configuration is valid
    func testConfigurationIsValid() {
        let configuration = BuildInfo.configuration

        // Configuration should be either "Debug" or "Release"
        XCTAssertTrue(configuration == "Debug" || configuration == "Release",
                     "Configuration should be 'Debug' or 'Release', got '\(configuration)'")
    }

    /// Test that debug configuration matches build settings
    func testConfigurationMatchesBuildSettings() {
        #if DEBUG
        XCTAssertEqual(BuildInfo.configuration, "Debug",
                      "Configuration should be 'Debug' in debug builds")
        #else
        XCTAssertEqual(BuildInfo.configuration, "Release",
                      "Configuration should be 'Release' in release builds")
        #endif
    }

    // MARK: - Integration Tests

    /// Test that all BuildInfo fields are accessible
    func testAllFieldsAccessible() {
        // This test ensures all fields can be accessed without runtime errors
        let version = BuildInfo.version
        let commitHash = BuildInfo.gitCommitHash
        let buildDate = BuildInfo.buildDate
        let configuration = BuildInfo.configuration

        XCTAssertNotNil(version)
        XCTAssertNotNil(commitHash)
        XCTAssertNotNil(buildDate)
        XCTAssertNotNil(configuration)
    }

    /// Test that BuildInfo is used by MiscViews
    func testBuildInfoIntegrationWithMiscViews() {
        // This test verifies that the getBuildInformation method exists
        // and returns values that match BuildInfo
        // We can't directly test the private method, but we can verify the values are correct
        XCTAssertEqual(BuildInfo.version, BuildInfo.version,
                      "BuildInfo.version should be consistent")
        XCTAssertEqual(BuildInfo.gitCommitHash, BuildInfo.gitCommitHash,
                      "BuildInfo.gitCommitHash should be consistent")
        XCTAssertEqual(BuildInfo.buildDate, BuildInfo.buildDate,
                      "BuildInfo.buildDate should be consistent")
        XCTAssertEqual(BuildInfo.configuration, BuildInfo.configuration,
                      "BuildInfo.configuration should be consistent")
    }

    // MARK: - String Representation Tests

    /// Test that version info can be formatted for display
    func testVersionInfoFormatting() {
        let versionString = "Version: \(BuildInfo.version)"
        let commitString = "Commit: \(BuildInfo.gitCommitHash)"
        let buildDateString = "Build Date: \(BuildInfo.buildDate)"
        let configString = "Configuration: \(BuildInfo.configuration)"

        XCTAssertFalse(versionString.isEmpty)
        XCTAssertFalse(commitString.isEmpty)
        XCTAssertFalse(buildDateString.isEmpty)
        XCTAssertFalse(configString.isEmpty)

        // Verify strings contain expected prefixes
        XCTAssertTrue(versionString.hasPrefix("Version: "))
        XCTAssertTrue(commitString.hasPrefix("Commit: "))
        XCTAssertTrue(buildDateString.hasPrefix("Build Date: "))
        XCTAssertTrue(configString.hasPrefix("Configuration: "))
    }

    /// Test that version info is suitable for logging
    func testVersionInfoLogging() {
        let logMessage = """
        Build Information:
        - Version: \(BuildInfo.version)
        - Commit: \(BuildInfo.gitCommitHash)
        - Build Date: \(BuildInfo.buildDate)
        - Configuration: \(BuildInfo.configuration)
        """

        XCTAssertFalse(logMessage.isEmpty, "Log message should not be empty")
        XCTAssertTrue(logMessage.contains("Build Information:"))
        XCTAssertTrue(logMessage.contains(BuildInfo.version))
        XCTAssertTrue(logMessage.contains(BuildInfo.gitCommitHash))
    }

    // MARK: - Compile-Time Embedding Tests

    /// Test that version info is embedded at compile time
    ///
    /// This test verifies that the BuildInfo values are not dynamically
    /// generated at runtime by checking they remain constant across calls
    func testVersionInfoIsCompileTimeConstant() {
        // Call multiple times and verify values don't change
        let version1 = BuildInfo.version
        let version2 = BuildInfo.version
        let version3 = BuildInfo.version

        XCTAssertEqual(version1, version2, "Version should be constant")
        XCTAssertEqual(version2, version3, "Version should be constant")

        let hash1 = BuildInfo.gitCommitHash
        let hash2 = BuildInfo.gitCommitHash

        XCTAssertEqual(hash1, hash2, "Commit hash should be constant")

        let date1 = BuildInfo.buildDate
        let date2 = BuildInfo.buildDate

        XCTAssertEqual(date1, date2, "Build date should be constant")

        let config1 = BuildInfo.configuration
        let config2 = BuildInfo.configuration

        XCTAssertEqual(config1, config2, "Configuration should be constant")
    }

    /// Test that BuildInfo is a compile-time constant by verifying type
    func testBuildInfoIsStaticEnum() {
        // BuildInfo should be an enum with static properties
        // This is a compile-time check - if it compiles, the test passes
        let _: String = BuildInfo.version
        let _: String = BuildInfo.gitCommitHash
        let _: String = BuildInfo.buildDate
        let _: String = BuildInfo.configuration

        // If we got here, the types are correct
        XCTAssertTrue(true, "BuildInfo properties are correctly typed as String")
    }
}
